server:
  port: 8080
spring:
  application:
    name: CUSTOMER-SERVICE
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customer-db
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
