server:
  port: 9000

spring:
  application:
    name: GATEWAY-SERVICE
#  main:
#    web-application-type: reactive
#    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ecommerce-app
            client-secret: PzP1SaROEhym1CE4bKT88LIpYRqSOpbz
            scope: openid, profile, email, roles
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_URL:localhost}:8080/realms/myapp
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - TokenRelay=
        - id: invoice
          uri: lb://INVOICE-SERVICE
          predicates:
            - Path=/api/invoices/**
          filters:
            - TokenRelay=
  zipkin:
    base-url: http://${ZIPKIN_URL:localhost}:9411
management:
  endpoints:
    web:
      exposure:
        include:  [ 'configprops', 'env', 'health', 'info', 'logfile', 'loggers' ]
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URL:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
      preferIpAddress: true
logging:
  level:
    org.springframework.security.*: trace
