server:
  port: 9000

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
        - id: invoice
          uri: lb://INVOICE-SERVICE
          predicates:
            - Path=/api/invoices/**
management:
  endpoints:
    web:
      exposure:
        include:  [ 'configprops', 'env', 'health', 'info', 'logfile', 'loggers' ]
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
